server:
  port: 8081

app:
  id: common-logging

spring:
  application:
    name: common-logging

  profiles:
    active: local

  jmx:
    enabled: true

  main:
    allow-bean-definition-overriding: true
